# https://www.reddit.com/r/pico8/comments/d2xsjy/extended_palette/
const
  black* = 0
  dark_blue* = 1
  dark_purple* = 2
  dark_green* = 3
  brown* = 4
  dark_grey* = 5
  light_grey* = 6
  white* = 7
  red* = 8
  orange* = 9
  yellow* = 10
  green* = 11
  blue* = 12
  dusk* = 13
  pink* = 14
  peach* = 15
  # secret pallette
  cocoa* = 16
  midnight* = 17
  port* = 18
  sea* = 19
  leather* = 20
  charcoal* = 21
  dark_tan* = 22
  sand* = 23
  crimson* = 24
  dark_orange* = 25
  yellow_green* = 26
  jade* = 27
  denim* = 28
  eggplant* = 29
  salmon* = 30
  coral* = 31